### ISSUE TITLE
attempting to run app locally; missing file 'meta_filter.fst'

### ISSUE THREAD

**Issue by whtns** [davemcg/plaeApp#23]
Don't see a link to this in the README or any hint. Is this something I generate myself?

**Comment by whtns** [comment]
should've checked elsewhere in the repo. seem to have a resolution [here](https://github.com/davemcg/plaeApp/blob/9ae867b4586ec47e22ca409bbed19590ed79527c/src/convert_metadata_to_fst.R)

**Comment by davemcg** [comment]
Argh, that should have been an step in the README. Will update. We also have a precomputed "meta_filter.fst" file available. Were you able to generate it?

**Comment by whtns** [comment]
yes! I got it to run. It was handy to run in that script in tmux because it took a while

**Comment by whtns** [comment]
maybe off topic...but I'm interested in the design of the database. Do you have anything that describes what each table is or why it was efficient to split them as you did?

**Comment by davemcg** [comment]
Readme updated with FST download: 2394400

**Comment by davemcg** [comment]
Database design...

You can see the tables by running:
```
> scEiaD_2020_v01 %>% db_list_tables()
 [1] "PB_Test_terms"              "PB_results"                 "celltype_labels"            "celltype_predict_labels"    "cluster_labels"             "cpm"                       
 [7] "doublets"                   "genes"                      "grouped_stats"              "haystack"                   "input_data"                 "metadata"                  
[13] "metadata_filter"            "tabulamuris_predict_labels"
```

VERY briefly:
PB_Test_terms: the differential tests run
PB_results: a HUGE table with ALL diff testing results
celltypes_labels: the "mean" UMAP 2D position of each to overlay the text
celltype_predict_labels: same, but for the predicted celltypes
tabulamuris_predict_labels: same, but for tabula muris
cluster_labels: same, but for the clusters
cpm: the count table (made LONG - every row is a cell/gene combo)
doublets: doublet scoring for each cell
genes: just the genes used
grouped_stats: this is an ODD file that was created by doing a huge number of `group_by` then `sum` operations to pre-compute all possible combinations. this is HUGE but running arbitrary searches (e.g. how many cells express genes A in muller glia and cones in these 4 studies) takes many seconds to run; too slow for a reactive web app)
haystack: haystack diff testing. currently not being displayed
input_data: what files went into scEiaD sqlite (sloppy versioning)
metadata: the metadata table
metadata_filter: the same metadata table. at one point I was cleaning the metadata during scEiaD creation

**Comment by davemcg** [comment]
Essentially the data is optimized for two things:

  - Loading speed (app can load within a few seconds)
  - Query speed (data pulled as fast as possible)

Computations are minimized wherever possible by pre-computing.
